# This is a GitHub Actions workflow for building and pushing a Docker image to Google Container Registry.
# It is used to build and push a Docker image to Docker Hub.

name: Docker Container Continuous Integration
description: Build and push a Docker image to Google Container Registry

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build the docker image
        run: docker build -t moabdelazem/noter:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "docker.io/moabdelazem/noter:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: push the image to docker hub
        run: |
          docker login -u moabdelazem -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker push moabdelazem/noter:latest
